export { default as Navbar } from '../NavBar/navBar'
export { default as Footer } from '../Footer'
export { default as HomeContent } from './Home/HomeContent'
export { default as AboutSection } from './About/AboutSection'
export { default as SkillSection } from './Skill/SkillSection'
export { default as ProjectSection } from './Project/ProjectSection'
export { default as ContactSection } from './Contact/ContactSection'
